name: Setup OpenSearch
inputs:
  opensearch-version:
    description: The OpenSearch version to download (if necessary) and use
  plugins:
    description: OpenSearch plugins to install
  config:
    description: Set config
  archive-path:
    description: Path to existing OpenSearch tar.gz archive (optional)
runs:
  using: node20
  main: index.js
